"""Template used by Alembic when generating new migration files.
"""
from alembic import op
import sqlalchemy as sa

% if context.autogenerate:
    # autogenerated
% endif

def upgrade():
    pass


def downgrade():
    pass
